default_platform(:android)

platform :android do
  desc "Run Flutter Tests"
  lane :tests do
    # نستخدم ../ للخروج من مجلد android والوصول للمجلد الرئيسي حيث يوجد مجلد الـ test
    sh("cd .. && flutter test")
  end

  desc "Build APK for testing"
  lane :build_only do
    # نفس الشيء هنا لضمان بناء التطبيق من المسار الصحيح
    sh("cd .. && flutter build apk --release")
  end
end