name: Android Fastlane with Build Test

on:
  push:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # أو النسخة اللي بتستخدمها
          working-directory: android # حدد مكان الـ Gemfile
          bundler-cache: true # بيسرع الـ Build المرات الجاية

      - name: Install Fastlane
        run: |
          cd android
          gem install fastlane
      # ---------------------------------------------

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run Fastlane Tests
        run: |
          cd android
          bundle exec fastlane tests